### ISSUE TITLE
Documentation not clear for me

### ISSUE THREAD

**Issue by seyfcom** [yceruto/money-bundle#12]
I'm sorry, I'm probably missing something stupid but I don't get how or where to use the yaml example you give.
The receipt did not create a yaml file, in twig.yaml, it wont be accepted. 
What did I miss?

that kind of code:
`money:
     formatters:
         intl:
             number_locale: 'en_US'
             number_style: 2 # \NumberFormatter::CURRENCY
             number_pattern: null
         bitcoin:
             fraction_digits: 8`

**Comment by yceruto** [comment]
Hey @seyfcom, this configuration is stored in the `config/packages/` directory, for instance `config/packages/money.yaml`. I've updated the documentation to clarify this.

As of now, there isn't a recipe for this bundle since the default values are adequate.
